## Katrina Johnson - DSB Unit 2.5.2

## Challenge: Make Your Own Regression Model

Now that you've spent some time playing with a sample multivariate linear regression model, it's time to make your own.

You've already gotten started by prepping the FBI:UCR Crime dataset (Thinkful mirror) in a previous assignment.

Using this data, build a regression model to predict property crimes. You can use the features you prepared in the previous assignment, new features of your own choosing, or a combination. The goal here is prediction rather than understanding mechanisms, so the focus is on creating a model that explains a lot of variance.

Submit a notebook with your model and a brief writeup of your feature engineering and selection process to submit and review with your mentor.

## My Steps for Completing DSB Unit 2.5.2 Challenge

1. Download two datasets.  
2. Run the predicitve model I created in challenge 2.3.3 on both data sets.   
3. Evaluate the results to find out how consistently the predictive model works.
4. Use error calculating mechanism I created to test the sentiment or span in the naive bayes' lessons to text for accuracy.
5. Use the methods I learned in DSB Unit 5.1 to calculate the CI, R^2, pvalue, and Intercept and coefficients.
6. Analyze the results of the calculations made in step 5, and write about them, and write about how to address any apparent problems that I notice.

training a model means using sklearn's fit() method.  
I will need X and a Y variables
X is every feature that I want to go into the model that is not the outcome feature.  For example, if I am predicting property crime, I kick property crime out of X and make property crime Y.

Then instantiate my linear regression model.  Next, I do the fit(X, Y).  This creates a linear regression model.
Afterwards, I can call the following methods on the model: score(X,Y) or a predict(X) 

If I use Y_pred = NameIGiveTheRegressionModel.predict(X)
Now, I can compare Y_pred to Y.  This will tell me the residual of the model against each data point.  (i.e. the residual is the distance between each data point and the line. There is one residual for each data point.  This is why I can plot the residual on the Y axis and also on the X axis.)

To eveluate how good a model is at dealing with new data, do not refit the model.  Why?  Because if you do, it will be a different model.

Take my Oregon crime statistic data, make sure it has the same number of features, and in the same order as the New York crime statistic data.  This is because the model ignores column titles.  It only looks at the order in which they appear in the data set.

For Oregon_df
X1 = all features I choose to use, except Property Crime.
Y1 = Property crime.

For df  ..which is the NY data - I have aleady done this:
X = all features I choose to use, except Property Crime.  Y = Property crime. (I could call these X_train...and Y_train)

Once I run the do everything to X1 and Y1 that I did to the NewYork X and Y and run (plug them into) the same model as the variable that will be fit, ...Then I can compare them using score(X,Y) and predict (Y) and score(X1, Y1) and predict(X1).

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns
from sklearn import linear_model
%matplotlib inline
pd.options.display.float_format = '{:.3f}'.format
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression
#from statsmodels.discrete.discrete_model import Logit
from sklearn import preprocessing
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report

# Suppress annoying harmless error.
import warnings
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

In [2]:
#plt.style.use('dark_background')

In [3]:
df = pd.read_excel('table_8_offenses_known_to_law_enforcement_new_york_by_city_2013.xls')
df

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NEW YORK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"by City, 2013",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(revised\ndefinition)1,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson3
4,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
8,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
9,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
10,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
19,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
20,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
23,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
25,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
26,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
27,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
29,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
326,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
327,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
328,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
330,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
334,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
335,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
336,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
337,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
338,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
339,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
344,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
345,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
348,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
350,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN
352,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#df.iloc[3]

In [5]:
df.columns = ['City', 'Population', 'Violent crime', 'Murder and non negligent manslaughter', 'Rape (revised definition) 1',
              'Rape (legacy definition) 2', 'Robbery', 'Aggravated assault', 'Property crime', 'Burglary', 'Larceny theft', 
              'Motor vehicle theft', 'Arson 3']

#df

In [6]:
df = df.drop(0)
df = df.drop(1)
df = df.drop(2)
df = df.drop(3)
df = df.drop(352)
df = df.drop(353)
df = df.drop(354)
df = df.drop(['Rape (revised definition) 1'], axis=1)
df = df.drop(['Arson 3'], axis=1)
df = df.drop(['City'], axis=1)
df

,Population,Violent crime,Murder and non negligent manslaughter,Rape (legacy definition) 2,Robbery,Aggravated assault,Property crime,Burglary,Larceny theft,Motor vehicle theft
4,1861,0,0,0,0,0,12,2,10,0
5,2577,3,0,0,0,3,24,3,20,1
6,2846,3,0,0,0,3,16,1,15,0
7,97956,791,8,30,227,526,4090,705,3243,142
8,6388,23,0,3,4,16,223,53,165,5
9,4089,5,0,0,3,2,46,10,36,0
10,1781,3,0,0,0,3,10,0,10,0
11,118296,107,1,7,31,68,2118,204,1882,32
12,9519,9,0,2,4,3,210,16,188,6
13,18182,30,0,0,12,18,405,99,291,15
14,2053,0,0,0,0,0,39,3,35,1
15,4523,5,0,0,3,2,33,4,28,1
16,658,0,0,0,0,0,2,0,2,0
17,2522,2,0,0,0,2,5,0,4,1
18,27270,96,1,20,22,53,859,132,721,6
19,3333,1,0,0,1,0,25,3,20,2
20,7473,5,0,0,1,4,88,10,77,1
21,5418,8,0,0,3,5,94,16,78,0
22,15374,57,0,7,13,37,559,103,454,2
23,5733,15,0,1,3,11,191,32,157,2
24,17627,5,0,0,1,4,156,26,127,3
25,34243,13,0,0,3,10,442,50,388,4
26,46304,284,3,19,101,161,2349,525,1767,57
27,1410,0,0,0,0,0,14,2,12,0
28,12001,8,0,1,0,7,99,20,72,7
29,1022,1,0,0,0,1,4,2,2,0
30,2325,2,0,0,0,2,24,4,20,0
31,2054,1,0,0,0,1,20,6,14,0
32,2065,4,0,0,1,3,31,9,20,2
33,2358,0,0,0,0,0,13,3,10,0
...,...,...,...,...,...,...,...,...,...,...
322,3642,3,0,0,0,3,83,22,59,2
323,615,0,0,0,0,0,0,0,0,0
324,12195,14,0,3,2,9,437,25,410,2
325,61686,361,7,27,102,225,2528,449,1997,82
326,27980,16,0,2,6,8,571,39,523,9
327,6887,18,1,2,1,14,142,13,124,5
328,27940,40,0,3,16,21,767,91,650,26
329,3012,6,0,1,0,5,68,18,50,0
330,3453,6,0,1,0,5,78,5,73,0
331,5828,2,0,0,1,1,58,5,51,2
332,8392,4,0,0,0,4,59,6,52,1
333,5175,11,0,0,3,8,194,23,169,2
334,28179,109,0,12,16,81,1165,169,953,43
335,10245,26,1,3,11,11,242,58,163,21
336,1862,6,0,0,0,6,92,10,80,2
337,4337,5,0,0,1,4,54,9,41,4
338,43777,21,0,2,3,16,469,101,361,7
339,1797,0,0,0,0,0,25,5,20,0
340,4574,11,0,1,0,10,164,32,129,3
341,1732,2,0,0,0,2,44,4,37,3
342,44821,35,1,1,9,24,896,166,710,20
343,2604,6,0,0,0,6,62,12,49,1
344,57559,78,1,3,28,46,1232,77,1134,21
345,3733,4,0,0,0,4,36,14,21,1
346,9141,0,0,0,0,0,77,13,61,3
347,10685,3,0,0,2,1,541,9,529,3
348,829,7,0,0,0,7,17,8,9,0
349,5931,2,0,0,0,2,58,13,45,0
350,199134,1036,6,25,390,615,2368,470,1662,236
351,36643,15,0,0,2,13,334,45,287,2

In [7]:
#df.isna().sum()

#df.findall({NaN}).any(axis=1).sum()
index = df['Rape (revised definition) 1'].index[df['Rape (revised definition) 1'].apply(np.isnan)]
index

## This is a more elegent solution for converting df['Robbery'] to a series of binary values:

df['Robbery binary'] = df['Robbery'].apply(lambda x: 1 if x > 0 else 0)

In [8]:
#Example: df.drop(columns=['B', 'C'])


print(df)
corr = df.corr()
print(corr)


#sns.heatmap(corr, xticklabels=corr.columns.values, 
#            yticklabels=corr.columns.values)

    Population Violent crime Murder and non negligent manslaughter  \
4         1861             0                                     0
5         2577             3                                     0
6         2846             3                                     0
7        97956           791                                     8
8         6388            23                                     0
9         4089             5                                     0
10        1781             3                                     0
11      118296           107                                     1
12        9519             9                                     0
13       18182            30                                     0
14        2053             0                                     0
15        4523             5                                     0
16         658             0                                     0
17        2522             2                                     0
18       27270            96                                     1
19        3333             1                                     0
20        7473             5                                     0
21        5418             8                                     0
22       15374            57                                     0
23        5733            15                                     0
24       17627             5                                     0
25       34243            13                                     0
26       46304           284                                     3
27        1410             0                                     0
28       12001             8                                     0
29        1022             1                                     0
30        2325             2                                     0
31        2054             1                                     0
32        2065             4                                     0
33        2358             0                                     0
..         ...           ...                                   ...
322       3642             3                                     0
323        615             0                                     0
324      12195            14                                     0
325      61686           361                                     7
326      27980            16                                     0
327       6887            18                                     1
328      27940            40                                     0
329       3012             6                                     0
330       3453             6                                     0
331       5828             2                                     0
332       8392             4                                     0
333       5175            11                                     0
334      28179           109                                     0
335      10245            26                                     1
336       1862             6                                     0
337       4337             5                                     0
338      43777            21                                     0
339       1797             0                                     0
340       4574            11                                     0
341       1732             2                                     0
342      44821            35                                     1
343       2604             6                                     0
344      57559            78                                     1
345       3733             4                                     0
346       9141             0                                     0
347      10685             3                                     0
348        829             7                                     0
349       5931             2                                     0
350     199134          1036                                     6
351      36643            15                                     0

    Rape (legacy definition) 2 Robbery Aggravated assault Property crime  \
4                            0       0                  0             12
5                            0       0                  3             24
6                            0       0                  3             16
7                           30     227                526           4090
8                            3       4                 16            223
9                            0       3                  2             46
10                           0       0                  3             10
11                           7      31                 68           2118
12                           2       4                  3            210
13                           0      12                 18            405
14                           0       0                  0             39
15                           0       3                  2             33
16                           0       0                  0              2
17                           0       0                  2              5
18                          20      22                 53            859
19                           0       1                  0             25
20                           0       1                  4             88
21                           0       3                  5             94
22                           7      13                 37            559
23                           1       3                 11            191
24                           0       1                  4            156
25                           0       3                 10            442
26                          19     101                161           2349
27                           0       0                  0             14
28                           1       0                  7             99
29                           0       0                  1              4
30                           0       0                  2             24
31                           0       0                  1             20
32                           0       1                  3             31
33                           0       0                  0             13
..                         ...     ...                ...            ...
322                          0       0                  3             83
323                          0       0                  0              0
324                          3       2                  9            437
325                         27     102                225           2528
326                          2       6                  8            571
327                          2       1                 14            142
328                          3      16                 21            767
329                          1       0                  5             68
330                          1       0                  5             78
331                          0       1                  1             58
332                          0       0                  4             59
333                          0       3                  8            194
334                         12      16                 81           1165
335                          3      11                 11            242
336                          0       0                  6             92
337                          0       1                  4             54
338                          2       3                 16            469
339                          0       0                  0             25
340                          1       0                 10            164
341                          0       0                  2             44
342                          1       9                 24            896
343                          0       0                  6             62
344                          3      28                 46           1232
345                          0       0                  4             36
346                          0       0                  0             77
347                          0       2                  1            541
348                          0       0                  7             17
349                          0       0                  2             58
350                         25     390                615           2368
351                          0       2                 13            334

    Burglary Larceny theft Motor vehicle theft
4          2            10                   0
5          3            20                   1
6          1            15                   0
7        705          3243                 142
8         53           165                   5
9         10            36                   0
10         0            10                   0
11       204          1882                  32
12        16           188                   6
13        99           291                  15
14         3            35                   1
15         4            28                   1
16         0             2                   0
17         0             4                   1
18       132           721                   6
19         3            20                   2
20        10            77                   1
21        16            78                   0
22       103           454                   2
23        32           157                   2
24        26           127                   3
25        50           388                   4
26       525          1767                  57
27         2            12                   0
28        20            72                   7
29         2             2                   0
30         4            20                   0
31         6            14                   0
32         9            20                   2
33         3            10                   0
..       ...           ...                 ...
322       22            59                   2
323        0             0                   0
324       25           410                   2
325      449          1997                  82
326       39           523                   9
327       13           124                   5
328       91           650                  26
329       18            50                   0
330        5            73                   0
331        5            51                   2
332        6            52                   1
333       23           169                   2
334      169           953                  43
335       58           163                  21
336       10            80                   2
337        9            41                   4
338      101           361                   7
339        5            20                   0
340       32           129                   3
341        4            37                   3
342      166           710                  20
343       12            49                   1
344       77          1134                  21
345       14            21                   1
346       13            61                   3
347        9           529                   3
348        8             9                   0
349       13            45                   0
350      470          1662                 236
351       45           287                   2

[348 rows x 10 columns]
Empty DataFrame
Columns: []
Index: []

Property Crimes:
    Robbery
    Burglary
    Larceny theft
    Motor vehicle theft
    
Features that (according to the heat map figures above) have a strong correlation with one or more fo the above features:

    Robbery -> top 4 correlates listed highest to lowest ->  Violent crime, Aggrevated assault, Larceny theft/Population
    
    Burglary -> top 4 correlates listed highest to lowest -> murder and non neglegent manslaughter, Rape (legacy definition) 2, Motor vehicle theft, Property crime
    
    Larceny theft -> top 4 correlates listed highest to lowest -> Property crime, Aggrevated assault/Robbery/Violent crime
    
    Motor vehicle theft -> top 6 correlates listed highest to lowest -> Rape (legacy definition) 2, murder and non neglegent manslaughter/Property crime, Violent crime/Robbery/Larceny theft
    
### Before doing the step in the bloc below: Divide every feature by the population, in order to normalize this data set.  This allows for explanations to be presented in a per capita basis.
Go to applymap documentation
make a lambda function that says for this column, divide this column by the population column.
Practice doing it for one column for example data['Burglary'] to find out whether or not it works.

data['Burglary'] = data['Burglary'] / data['Population']

# Acquire, load, and preview the data.
data = pd.read_csv('https://tf-curricula-prod.s3.amazonaws.com/data-science/Advertising.csv')
display(data.head())

# Instantiate and fit our model.
regr = linear_model.LinearRegression()
Y = data['Sales'].values.reshape(-1, 1)
X = data[['TV','Radio','Newspaper']]
regr.fit(X, Y)

# Inspect the results.
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X, Y))

#Example of how to use the applymap function, and how to write a lambda function.
df.applymap(lambda x: len(str(x)))

In [9]:
df.columns

Index(['Population', 'Violent crime', 'Murder and non negligent manslaughter',
       'Rape (legacy definition) 2', 'Robbery', 'Aggravated assault',
       'Property crime', 'Burglary', 'Larceny theft', 'Motor vehicle theft'],
      dtype='object')

In [10]:
df.describe

<bound method NDFrame.describe of     Population Violent crime Murder and non negligent manslaughter  \
4         1861             0                                     0
5         2577             3                                     0
6         2846             3                                     0
7        97956           791                                     8
8         6388            23                                     0
9         4089             5                                     0
10        1781             3                                     0
11      118296           107                                     1
12        9519             9                                     0
13       18182            30                                     0
14        2053             0                                     0
15        4523             5                                     0
16         658             0                                     0
17        2522             2                                     0
18       27270            96                                     1
19        3333             1                                     0
20        7473             5                                     0
21        5418             8                                     0
22       15374            57                                     0
23        5733            15                                     0
24       17627             5                                     0
25       34243            13                                     0
26       46304           284                                     3
27        1410             0                                     0
28       12001             8                                     0
29        1022             1                                     0
30        2325             2                                     0
31        2054             1                                     0
32        2065             4                                     0
33        2358             0                                     0
..         ...           ...                                   ...
322       3642             3                                     0
323        615             0                                     0
324      12195            14                                     0
325      61686           361                                     7
326      27980            16                                     0
327       6887            18                                     1
328      27940            40                                     0
329       3012             6                                     0
330       3453             6                                     0
331       5828             2                                     0
332       8392             4                                     0
333       5175            11                                     0
334      28179           109                                     0
335      10245            26                                     1
336       1862             6                                     0
337       4337             5                                     0
338      43777            21                                     0
339       1797             0                                     0
340       4574            11                                     0
341       1732             2                                     0
342      44821            35                                     1
343       2604             6                                     0
344      57559            78                                     1
345       3733             4                                     0
346       9141             0                                     0
347      10685             3                                     0
348        829             7                                     0
349       5931             2                                     0
350     199134          1036                                     6
351      36643            15                                     0

    Rape (legacy definition) 2 Robbery Aggravated assault Property crime  \
4                            0       0                  0             12
5                            0       0                  3             24
6                            0       0                  3             16
7                           30     227                526           4090
8                            3       4                 16            223
9                            0       3                  2             46
10                           0       0                  3             10
11                           7      31                 68           2118
12                           2       4                  3            210
13                           0      12                 18            405
14                           0       0                  0             39
15                           0       3                  2             33
16                           0       0                  0              2
17                           0       0                  2              5
18                          20      22                 53            859
19                           0       1                  0             25
20                           0       1                  4             88
21                           0       3                  5             94
22                           7      13                 37            559
23                           1       3                 11            191
24                           0       1                  4            156
25                           0       3                 10            442
26                          19     101                161           2349
27                           0       0                  0             14
28                           1       0                  7             99
29                           0       0                  1              4
30                           0       0                  2             24
31                           0       0                  1             20
32                           0       1                  3             31
33                           0       0                  0             13
..                         ...     ...                ...            ...
322                          0       0                  3             83
323                          0       0                  0              0
324                          3       2                  9            437
325                         27     102                225           2528
326                          2       6                  8            571
327                          2       1                 14            142
328                          3      16                 21            767
329                          1       0                  5             68
330                          1       0                  5             78
331                          0       1                  1             58
332                          0       0                  4             59
333                          0       3                  8            194
334                         12      16                 81           1165
335                          3      11                 11            242
336                          0       0                  6             92
337                          0       1                  4             54
338                          2       3                 16            469
339                          0       0                  0             25
340                          1       0                 10            164
341                          0       0                  2             44
342                          1       9                 24            896
343                          0       0                  6             62
344                          3      28                 46           1232
345                          0       0                  4             36
346                          0       0                  0             77
347                          0       2                  1            541
348                          0       0                  7             17
349                          0       0                  2             58
350                         25     390                615           2368
351                          0       2                 13            334

    Burglary Larceny theft Motor vehicle theft
4          2            10                   0
5          3            20                   1
6          1            15                   0
7        705          3243                 142
8         53           165                   5
9         10            36                   0
10         0            10                   0
11       204          1882                  32
12        16           188                   6
13        99           291                  15
14         3            35                   1
15         4            28                   1
16         0             2                   0
17         0             4                   1
18       132           721                   6
19         3            20                   2
20        10            77                   1
21        16            78                   0
22       103           454                   2
23        32           157                   2
24        26           127                   3
25        50           388                   4
26       525          1767                  57
27         2            12                   0
28        20            72                   7
29         2             2                   0
30         4            20                   0
31         6            14                   0
32         9            20                   2
33         3            10                   0
..       ...           ...                 ...
322       22            59                   2
323        0             0                   0
324       25           410                   2
325      449          1997                  82
326       39           523                   9
327       13           124                   5
328       91           650                  26
329       18            50                   0
330        5            73                   0
331        5            51                   2
332        6            52                   1
333       23           169                   2
334      169           953                  43
335       58           163                  21
336       10            80                   2
337        9            41                   4
338      101           361                   7
339        5            20                   0
340       32           129                   3
341        4            37                   3
342      166           710                  20
343       12            49                   1
344       77          1134                  21
345       14            21                   1
346       13            61                   3
347        9           529                   3
348        8             9                   0
349       13            45                   0
350      470          1662                 236
351       45           287                   2

[348 rows x 10 columns]>

In [11]:
#df['Burglary']

In [12]:
#df = df.drop(['City'], axis=1)

In [13]:
df.columns

Index(['Population', 'Violent crime', 'Murder and non negligent manslaughter',
       'Rape (legacy definition) 2', 'Robbery', 'Aggravated assault',
       'Property crime', 'Burglary', 'Larceny theft', 'Motor vehicle theft'],
      dtype='object')


#Nice example of a lambda function. Not sure whether or not it works.
#df.loc[df['Rape (revised definition) 1'].apply(lambda x: x == int(x))]

lambda x: ((for x in df): x/ 'Population').

df['violent_crime_div_pop'] = df['Violent crime'].fillna(0).astype('int') / df['Population']
df['Murder_and_non_negligent_manslaughter_div_pop'] = df['Murder and non negligent manslaughter'].fillna(0).astype('int') / df['Population']

In [14]:
#df

In [15]:
Oregon_df = pd.read_excel('table_8_offenses_known_to_law_enforcement_oregon_by_city_2013.xls')
#Oregon_df

In [16]:
Oregon_df.iloc[3]

Table 8                                          City
Unnamed: 1                                 Population
Unnamed: 2                             Violent\ncrime
Unnamed: 3     Murder and\nnonnegligent\nmanslaughter
Unnamed: 4               Rape\n(revised\ndefinition)1
Unnamed: 5                Rape\n(legacy\ndefinition)2
Unnamed: 6                                    Robbery
Unnamed: 7                        Aggravated\nassault
Unnamed: 8                            Property\ncrime
Unnamed: 9                                   Burglary
Unnamed: 10                           Larceny-\ntheft
Unnamed: 11                     Motor\nvehicle\ntheft
Unnamed: 12                                     Arson
Name: 3, dtype: object

In [17]:
Oregon_df.columns = ['City', 'Population', 'Violent crime', 'Murder and nonnegligent manslaughter', 
                     'Rape (revised definition) 1','Rape (legacy definition) 2', 'Robbery', 'Aggravated assault',
                     'Property crime', 'Burglary', 'Larceny-theft', 'Motor vehicle theft', 'Arson']
#Oregon_df

In [18]:
Oregon_df = Oregon_df.iloc[4:]
Oregon_df = Oregon_df.drop(113)
Oregon_df = Oregon_df.drop(114)
Oregon_df

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition) 1,Rape (legacy definition) 2,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft,Arson
4,Albany,51645,40,0,NaN,8,27,5,2019,252,1625,142,6
5,Amity,1624,1,0,1,NaN,0,0,26,1,25,0,1
6,Ashland,20455,33,0,5,NaN,7,21,674,76,585,13,10
7,Astoria,9543,33,0,NaN,3,1,29,445,89,324,32,3
8,Athena,1144,1,0,1,NaN,0,0,25,5,19,1,0
9,Aumsville,3738,6,0,0,NaN,1,5,82,20,59,3,0
10,Baker City,9660,27,0,NaN,1,2,24,370,68,293,9,5
11,Bandon,3039,1,0,NaN,0,1,0,88,24,59,5,1
12,Banks,1862,4,0,NaN,0,0,4,26,5,17,4,1
13,Beaverton,93551,124,1,NaN,20,22,81,1471,175,1213,83,15
14,Bend,79926,182,1,21,NaN,22,138,2267,267,1913,87,39
15,Black Butte,NaN,0,0,0,NaN,0,0,5,0,5,0,0
16,Boardman,3369,8,0,3,NaN,0,5,84,22,58,4,0
17,Brookings,6313,2,0,NaN,0,1,1,55,6,43,6,0
18,Burns,2706,1,0,NaN,0,0,1,66,19,43,4,0
19,Canby,16031,13,0,NaN,4,2,7,298,60,229,9,3
20,Cannon Beach,1692,1,0,NaN,0,0,1,38,1,35,2,0
21,Carlton,2022,4,0,3,NaN,0,1,18,3,15,0,0
22,Central Point,17485,33,0,5,NaN,4,24,601,47,530,24,6
23,Clatskanie,1726,0,0,NaN,0,0,0,51,19,28,4,0
24,Coburg,1043,0,0,NaN,0,0,0,15,5,9,1,0
25,Columbia City,1938,0,0,0,NaN,0,0,11,0,10,1,0
26,Condon,722,0,0,NaN,0,0,0,2,0,2,0,0
27,Coos Bay,15816,60,1,NaN,3,6,50,965,166,745,54,3
28,Coquille,3826,0,0,NaN,0,0,0,67,12,51,4,0
29,Cornelius,12231,18,0,NaN,4,9,5,351,66,271,14,1
30,Corvallis,55218,64,0,10,NaN,16,38,1587,195,1354,38,8
31,Cottage Grove,9795,18,1,NaN,0,5,12,509,52,436,21,0
32,Dallas,14803,41,0,6,NaN,4,31,315,51,254,10,2
33,Eagle Point,8669,24,0,4,NaN,8,12,344,43,294,7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,Prineville,9161,24,0,NaN,1,1,22,295,45,249,1,2
84,Rainier,1887,2,0,NaN,0,1,1,43,6,33,4,0
85,Redmond,27153,87,0,11,NaN,15,61,1067,157,867,43,11
86,Rockaway Beach,1313,2,0,0,NaN,0,2,48,20,28,0,0
87,Rogue River,2173,2,0,0,NaN,0,2,45,7,33,5,0
88,Salem,158234,520,7,47,NaN,138,328,6782,983,5143,656,42
89,Scappoose,6677,11,0,NaN,0,1,10,82,14,66,2,1
90,Seaside,6475,8,0,NaN,2,4,2,554,74,465,15,1
91,Sherwood,18932,8,0,NaN,2,2,4,301,31,260,10,3
92,Silverton,9380,10,1,2,NaN,3,4,207,28,173,6,3
93,Springfield,60024,98,2,14,NaN,32,50,3198,478,2450,270,25
94,Stanfield,2058,2,0,1,NaN,0,1,29,6,19,4,0
95,Stayton,7733,23,0,3,NaN,5,15,337,46,278,13,1
96,St. Helens,12917,9,0,NaN,5,2,2,353,46,291,16,3
97,Sunriver,NaN,2,0,0,NaN,0,2,80,16,60,4,0
98,Sweet Home,9035,10,0,NaN,1,4,5,501,82,398,21,0
99,Talent,6191,7,0,2,NaN,0,5,131,12,115,4,1
100,The Dalles,13831,14,0,NaN,1,6,7,692,141,513,38,4
101,Tigard,50311,57,0,NaN,14,23,20,1626,173,1384,69,10
102,Tillamook,4932,10,0,1,NaN,4,5,177,23,142,12,2
103,Toledo,3461,16,1,2,NaN,2,11,145,37,103,5,0
104,Troutdale,16566,22,0,NaN,3,9,10,509,64,396,49,5
105,Tualatin,26925,24,0,NaN,7,9,8,783,88,658,37,3
106,Turner,1896,1,1,0,NaN,0,0,24,7,15,2,0
107,Umatilla,7040,13,0,2,NaN,0,11,107,25,70,12,1
108,Warrenton,5146,0,0,NaN,0,0,0,167,25,134,8,0
109,West Linn,25744,6,0,NaN,3,0,3,279,36,234,9,2
110,Wilsonville,20819,17,0,NaN,6,6,5,461,51,374,36,2
111,Woodburn,24263,82,1,7,NaN,28,46,733,100,586,47,7
112,Yamhill,1040,0,0,0,NaN,0,0,16,3,13,0,0

In [19]:
Oregon_df = Oregon_df.drop(['City'], axis=1)
Oregon_df = Oregon_df.drop(['Rape (revised definition) 1'], axis=1)
Oregon_df = Oregon_df.drop(['Arson'], axis=1)

In [20]:
Oregon_df.dtypes

Population                              object
Violent crime                           object
Murder and nonnegligent manslaughter    object
Rape (legacy definition) 2              object
Robbery                                 object
Aggravated assault                      object
Property crime                          object
Burglary                                object
Larceny-theft                           object
Motor vehicle theft                     object
dtype: object

In [21]:
Oregon_df['Rape (legacy definition) 2'] = Oregon_df['Rape (legacy definition) 2'].fillna(Oregon_df['Rape (legacy definition) 2'].mean())

Oregon_df

,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (legacy definition) 2,Robbery,Aggravated assault,Property crime,Burglary,Larceny-theft,Motor vehicle theft
4,51645,40,0,8.000,27,5,2019,252,1625,142
5,1624,1,0,8.000,0,0,26,1,25,0
6,20455,33,0,8.000,7,21,674,76,585,13
7,9543,33,0,3.000,1,29,445,89,324,32
8,1144,1,0,8.000,0,0,25,5,19,1
9,3738,6,0,8.000,1,5,82,20,59,3
10,9660,27,0,1.000,2,24,370,68,293,9
11,3039,1,0,0.000,1,0,88,24,59,5
12,1862,4,0,0.000,0,4,26,5,17,4
13,93551,124,1,20.000,22,81,1471,175,1213,83
14,79926,182,1,8.000,22,138,2267,267,1913,87
15,NaN,0,0,8.000,0,0,5,0,5,0
16,3369,8,0,8.000,0,5,84,22,58,4
17,6313,2,0,0.000,1,1,55,6,43,6
18,2706,1,0,0.000,0,1,66,19,43,4
19,16031,13,0,4.000,2,7,298,60,229,9
20,1692,1,0,0.000,0,1,38,1,35,2
21,2022,4,0,8.000,0,1,18,3,15,0
22,17485,33,0,8.000,4,24,601,47,530,24
23,1726,0,0,0.000,0,0,51,19,28,4
24,1043,0,0,0.000,0,0,15,5,9,1
25,1938,0,0,8.000,0,0,11,0,10,1
26,722,0,0,0.000,0,0,2,0,2,0
27,15816,60,1,3.000,6,50,965,166,745,54
28,3826,0,0,0.000,0,0,67,12,51,4
29,12231,18,0,4.000,9,5,351,66,271,14
30,55218,64,0,8.000,16,38,1587,195,1354,38
31,9795,18,1,0.000,5,12,509,52,436,21
32,14803,41,0,8.000,4,31,315,51,254,10
33,8669,24,0,8.000,8,12,344,43,294,7
...,...,...,...,...,...,...,...,...,...,...
83,9161,24,0,1.000,1,22,295,45,249,1
84,1887,2,0,0.000,1,1,43,6,33,4
85,27153,87,0,8.000,15,61,1067,157,867,43
86,1313,2,0,8.000,0,2,48,20,28,0
87,2173,2,0,8.000,0,2,45,7,33,5
88,158234,520,7,8.000,138,328,6782,983,5143,656
89,6677,11,0,0.000,1,10,82,14,66,2
90,6475,8,0,2.000,4,2,554,74,465,15
91,18932,8,0,2.000,2,4,301,31,260,10
92,9380,10,1,8.000,3,4,207,28,173,6
93,60024,98,2,8.000,32,50,3198,478,2450,270
94,2058,2,0,8.000,0,1,29,6,19,4
95,7733,23,0,8.000,5,15,337,46,278,13
96,12917,9,0,5.000,2,2,353,46,291,16
97,NaN,2,0,8.000,0,2,80,16,60,4
98,9035,10,0,1.000,4,5,501,82,398,21
99,6191,7,0,8.000,0,5,131,12,115,4
100,13831,14,0,1.000,6,7,692,141,513,38
101,50311,57,0,14.000,23,20,1626,173,1384,69
102,4932,10,0,8.000,4,5,177,23,142,12
103,3461,16,1,8.000,2,11,145,37,103,5
104,16566,22,0,3.000,9,10,509,64,396,49
105,26925,24,0,7.000,9,8,783,88,658,37
106,1896,1,1,8.000,0,0,24,7,15,2
107,7040,13,0,8.000,0,11,107,25,70,12
108,5146,0,0,0.000,0,0,167,25,134,8
109,25744,6,0,3.000,0,3,279,36,234,9
110,20819,17,0,6.000,6,5,461,51,374,36
111,24263,82,1,8.000,28,46,733,100,586,47
112,1040,0,0,8.000,0,0,16,3,13,0

Oregon_corr = Oregon_df.corr()
sns.heatmap(corr, xticklabels=corr.columns.values,
           yticklabels=corr.columns.values)

# My Unit 3.3.4 Challenge Work Begins Here:

In [22]:
df

,Population,Violent crime,Murder and non negligent manslaughter,Rape (legacy definition) 2,Robbery,Aggravated assault,Property crime,Burglary,Larceny theft,Motor vehicle theft
4,1861,0,0,0,0,0,12,2,10,0
5,2577,3,0,0,0,3,24,3,20,1
6,2846,3,0,0,0,3,16,1,15,0
7,97956,791,8,30,227,526,4090,705,3243,142
8,6388,23,0,3,4,16,223,53,165,5
9,4089,5,0,0,3,2,46,10,36,0
10,1781,3,0,0,0,3,10,0,10,0
11,118296,107,1,7,31,68,2118,204,1882,32
12,9519,9,0,2,4,3,210,16,188,6
13,18182,30,0,0,12,18,405,99,291,15
14,2053,0,0,0,0,0,39,3,35,1
15,4523,5,0,0,3,2,33,4,28,1
16,658,0,0,0,0,0,2,0,2,0
17,2522,2,0,0,0,2,5,0,4,1
18,27270,96,1,20,22,53,859,132,721,6
19,3333,1,0,0,1,0,25,3,20,2
20,7473,5,0,0,1,4,88,10,77,1
21,5418,8,0,0,3,5,94,16,78,0
22,15374,57,0,7,13,37,559,103,454,2
23,5733,15,0,1,3,11,191,32,157,2
24,17627,5,0,0,1,4,156,26,127,3
25,34243,13,0,0,3,10,442,50,388,4
26,46304,284,3,19,101,161,2349,525,1767,57
27,1410,0,0,0,0,0,14,2,12,0
28,12001,8,0,1,0,7,99,20,72,7
29,1022,1,0,0,0,1,4,2,2,0
30,2325,2,0,0,0,2,24,4,20,0
31,2054,1,0,0,0,1,20,6,14,0
32,2065,4,0,0,1,3,31,9,20,2
33,2358,0,0,0,0,0,13,3,10,0
...,...,...,...,...,...,...,...,...,...,...
322,3642,3,0,0,0,3,83,22,59,2
323,615,0,0,0,0,0,0,0,0,0
324,12195,14,0,3,2,9,437,25,410,2
325,61686,361,7,27,102,225,2528,449,1997,82
326,27980,16,0,2,6,8,571,39,523,9
327,6887,18,1,2,1,14,142,13,124,5
328,27940,40,0,3,16,21,767,91,650,26
329,3012,6,0,1,0,5,68,18,50,0
330,3453,6,0,1,0,5,78,5,73,0
331,5828,2,0,0,1,1,58,5,51,2
332,8392,4,0,0,0,4,59,6,52,1
333,5175,11,0,0,3,8,194,23,169,2
334,28179,109,0,12,16,81,1165,169,953,43
335,10245,26,1,3,11,11,242,58,163,21
336,1862,6,0,0,0,6,92,10,80,2
337,4337,5,0,0,1,4,54,9,41,4
338,43777,21,0,2,3,16,469,101,361,7
339,1797,0,0,0,0,0,25,5,20,0
340,4574,11,0,1,0,10,164,32,129,3
341,1732,2,0,0,0,2,44,4,37,3
342,44821,35,1,1,9,24,896,166,710,20
343,2604,6,0,0,0,6,62,12,49,1
344,57559,78,1,3,28,46,1232,77,1134,21
345,3733,4,0,0,0,4,36,14,21,1
346,9141,0,0,0,0,0,77,13,61,3
347,10685,3,0,0,2,1,541,9,529,3
348,829,7,0,0,0,7,17,8,9,0
349,5931,2,0,0,0,2,58,13,45,0
350,199134,1036,6,25,390,615,2368,470,1662,236
351,36643,15,0,0,2,13,334,45,287,2

In [23]:
high_crime = (df['Property crime'] >= 1000).value_counts()

print(high_crime)

False    318
True      30
Name: Property crime, dtype: int64

In [24]:
low_crime = (df['Property crime'] <= 200).value_counts()

print(low_crime)

True     223
False    125
Name: Property crime, dtype: int64

In [25]:
#print(df['Property crime'])

In [26]:
df.insert(0, 'Property crime binary', '')

#df

In [27]:
#binary_pc = df.loc[df['Property crime']]
#print(binary_pc)

property_crime_binary = []


for item in df['Property crime']:
    if item >= 101:
        property_crime_binary.append(True)
    elif item <= 100:
        property_crime_binary.append(False)

In [28]:
df['Property crime binary'] = property_crime_binary

df

,Property crime binary,Population,Violent crime,Murder and non negligent manslaughter,Rape (legacy definition) 2,Robbery,Aggravated assault,Property crime,Burglary,Larceny theft,Motor vehicle theft
4,False,1861,0,0,0,0,0,12,2,10,0
5,False,2577,3,0,0,0,3,24,3,20,1
6,False,2846,3,0,0,0,3,16,1,15,0
7,True,97956,791,8,30,227,526,4090,705,3243,142
8,True,6388,23,0,3,4,16,223,53,165,5
9,False,4089,5,0,0,3,2,46,10,36,0
10,False,1781,3,0,0,0,3,10,0,10,0
11,True,118296,107,1,7,31,68,2118,204,1882,32
12,True,9519,9,0,2,4,3,210,16,188,6
13,True,18182,30,0,0,12,18,405,99,291,15
14,False,2053,0,0,0,0,0,39,3,35,1
15,False,4523,5,0,0,3,2,33,4,28,1
16,False,658,0,0,0,0,0,2,0,2,0
17,False,2522,2,0,0,0,2,5,0,4,1
18,True,27270,96,1,20,22,53,859,132,721,6
19,False,3333,1,0,0,1,0,25,3,20,2
20,False,7473,5,0,0,1,4,88,10,77,1
21,False,5418,8,0,0,3,5,94,16,78,0
22,True,15374,57,0,7,13,37,559,103,454,2
23,True,5733,15,0,1,3,11,191,32,157,2
24,True,17627,5,0,0,1,4,156,26,127,3
25,True,34243,13,0,0,3,10,442,50,388,4
26,True,46304,284,3,19,101,161,2349,525,1767,57
27,False,1410,0,0,0,0,0,14,2,12,0
28,False,12001,8,0,1,0,7,99,20,72,7
29,False,1022,1,0,0,0,1,4,2,2,0
30,False,2325,2,0,0,0,2,24,4,20,0
31,False,2054,1,0,0,0,1,20,6,14,0
32,False,2065,4,0,0,1,3,31,9,20,2
33,False,2358,0,0,0,0,0,13,3,10,0
...,...,...,...,...,...,...,...,...,...,...,...
322,False,3642,3,0,0,0,3,83,22,59,2
323,False,615,0,0,0,0,0,0,0,0,0
324,True,12195,14,0,3,2,9,437,25,410,2
325,True,61686,361,7,27,102,225,2528,449,1997,82
326,True,27980,16,0,2,6,8,571,39,523,9
327,True,6887,18,1,2,1,14,142,13,124,5
328,True,27940,40,0,3,16,21,767,91,650,26
329,False,3012,6,0,1,0,5,68,18,50,0
330,False,3453,6,0,1,0,5,78,5,73,0
331,False,5828,2,0,0,1,1,58,5,51,2
332,False,8392,4,0,0,0,4,59,6,52,1
333,True,5175,11,0,0,3,8,194,23,169,2
334,True,28179,109,0,12,16,81,1165,169,953,43
335,True,10245,26,1,3,11,11,242,58,163,21
336,False,1862,6,0,0,0,6,92,10,80,2
337,False,4337,5,0,0,1,4,54,9,41,4
338,True,43777,21,0,2,3,16,469,101,361,7
339,False,1797,0,0,0,0,0,25,5,20,0
340,True,4574,11,0,1,0,10,164,32,129,3
341,False,1732,2,0,0,0,2,44,4,37,3
342,True,44821,35,1,1,9,24,896,166,710,20
343,False,2604,6,0,0,0,6,62,12,49,1
344,True,57559,78,1,3,28,46,1232,77,1134,21
345,False,3733,4,0,0,0,4,36,14,21,1
346,False,9141,0,0,0,0,0,77,13,61,3
347,True,10685,3,0,0,2,1,541,9,529,3
348,False,829,7,0,0,0,7,17,8,9,0
349,False,5931,2,0,0,0,2,58,13,45,0
350,True,199134,1036,6,25,390,615,2368,470,1662,236
351,True,36643,15,0,0,2,13,334,45,287,2

In [29]:
x = df.iloc[0:348, 1:9]

x

,Population,Violent crime,Murder and non negligent manslaughter,Rape (legacy definition) 2,Robbery,Aggravated assault,Property crime,Burglary
4,1861,0,0,0,0,0,12,2
5,2577,3,0,0,0,3,24,3
6,2846,3,0,0,0,3,16,1
7,97956,791,8,30,227,526,4090,705
8,6388,23,0,3,4,16,223,53
9,4089,5,0,0,3,2,46,10
10,1781,3,0,0,0,3,10,0
11,118296,107,1,7,31,68,2118,204
12,9519,9,0,2,4,3,210,16
13,18182,30,0,0,12,18,405,99
14,2053,0,0,0,0,0,39,3
15,4523,5,0,0,3,2,33,4
16,658,0,0,0,0,0,2,0
17,2522,2,0,0,0,2,5,0
18,27270,96,1,20,22,53,859,132
19,3333,1,0,0,1,0,25,3
20,7473,5,0,0,1,4,88,10
21,5418,8,0,0,3,5,94,16
22,15374,57,0,7,13,37,559,103
23,5733,15,0,1,3,11,191,32
24,17627,5,0,0,1,4,156,26
25,34243,13,0,0,3,10,442,50
26,46304,284,3,19,101,161,2349,525
27,1410,0,0,0,0,0,14,2
28,12001,8,0,1,0,7,99,20
29,1022,1,0,0,0,1,4,2
30,2325,2,0,0,0,2,24,4
31,2054,1,0,0,0,1,20,6
32,2065,4,0,0,1,3,31,9
33,2358,0,0,0,0,0,13,3
...,...,...,...,...,...,...,...,...
322,3642,3,0,0,0,3,83,22
323,615,0,0,0,0,0,0,0
324,12195,14,0,3,2,9,437,25
325,61686,361,7,27,102,225,2528,449
326,27980,16,0,2,6,8,571,39
327,6887,18,1,2,1,14,142,13
328,27940,40,0,3,16,21,767,91
329,3012,6,0,1,0,5,68,18
330,3453,6,0,1,0,5,78,5
331,5828,2,0,0,1,1,58,5
332,8392,4,0,0,0,4,59,6
333,5175,11,0,0,3,8,194,23
334,28179,109,0,12,16,81,1165,169
335,10245,26,1,3,11,11,242,58
336,1862,6,0,0,0,6,92,10
337,4337,5,0,0,1,4,54,9
338,43777,21,0,2,3,16,469,101
339,1797,0,0,0,0,0,25,5
340,4574,11,0,1,0,10,164,32
341,1732,2,0,0,0,2,44,4
342,44821,35,1,1,9,24,896,166
343,2604,6,0,0,0,6,62,12
344,57559,78,1,3,28,46,1232,77
345,3733,4,0,0,0,4,36,14
346,9141,0,0,0,0,0,77,13
347,10685,3,0,0,2,1,541,9
348,829,7,0,0,0,7,17,8
349,5931,2,0,0,0,2,58,13
350,199134,1036,6,25,390,615,2368,470
351,36643,15,0,0,2,13,334,45

In [30]:
#y = df.iloc[0:348, 0]

#y

In [31]:
x_train = df.iloc[0:281, 1:11]
print(x_train.shape)
type(x_train)

(281, 10)

pandas.core.frame.DataFrame

In [32]:
y_train = df.iloc[0:281, 0]
print(y_train.shape)
type(y_train)

(281,)

pandas.core.series.Series

In [33]:
x_test = df.iloc[282:348, 1:11]

#x_test

In [34]:
y_test = df.iloc[282:348, 0]

#y_test

In [35]:
#How to fit a binary logistic model

#step 3a.

sns.set_style('white')

## The following code creates test and train splits for you autmatically, and lets you set the amount of test #split.

#x_train, x_test, y_train, y_test = train_test_split(x,y, stratify=y, test_size=0.25)

#print(x_train.shape, y_train.shape)
#print(x_test.shape, y_test.shape)

# Vanilla logistic regression

In [36]:

df

,Property crime binary,Population,Violent crime,Murder and non negligent manslaughter,Rape (legacy definition) 2,Robbery,Aggravated assault,Property crime,Burglary,Larceny theft,Motor vehicle theft
4,False,1861,0,0,0,0,0,12,2,10,0
5,False,2577,3,0,0,0,3,24,3,20,1
6,False,2846,3,0,0,0,3,16,1,15,0
7,True,97956,791,8,30,227,526,4090,705,3243,142
8,True,6388,23,0,3,4,16,223,53,165,5
9,False,4089,5,0,0,3,2,46,10,36,0
10,False,1781,3,0,0,0,3,10,0,10,0
11,True,118296,107,1,7,31,68,2118,204,1882,32
12,True,9519,9,0,2,4,3,210,16,188,6
13,True,18182,30,0,0,12,18,405,99,291,15
14,False,2053,0,0,0,0,0,39,3,35,1
15,False,4523,5,0,0,3,2,33,4,28,1
16,False,658,0,0,0,0,0,2,0,2,0
17,False,2522,2,0,0,0,2,5,0,4,1
18,True,27270,96,1,20,22,53,859,132,721,6
19,False,3333,1,0,0,1,0,25,3,20,2
20,False,7473,5,0,0,1,4,88,10,77,1
21,False,5418,8,0,0,3,5,94,16,78,0
22,True,15374,57,0,7,13,37,559,103,454,2
23,True,5733,15,0,1,3,11,191,32,157,2
24,True,17627,5,0,0,1,4,156,26,127,3
25,True,34243,13,0,0,3,10,442,50,388,4
26,True,46304,284,3,19,101,161,2349,525,1767,57
27,False,1410,0,0,0,0,0,14,2,12,0
28,False,12001,8,0,1,0,7,99,20,72,7
29,False,1022,1,0,0,0,1,4,2,2,0
30,False,2325,2,0,0,0,2,24,4,20,0
31,False,2054,1,0,0,0,1,20,6,14,0
32,False,2065,4,0,0,1,3,31,9,20,2
33,False,2358,0,0,0,0,0,13,3,10,0
...,...,...,...,...,...,...,...,...,...,...,...
322,False,3642,3,0,0,0,3,83,22,59,2
323,False,615,0,0,0,0,0,0,0,0,0
324,True,12195,14,0,3,2,9,437,25,410,2
325,True,61686,361,7,27,102,225,2528,449,1997,82
326,True,27980,16,0,2,6,8,571,39,523,9
327,True,6887,18,1,2,1,14,142,13,124,5
328,True,27940,40,0,3,16,21,767,91,650,26
329,False,3012,6,0,1,0,5,68,18,50,0
330,False,3453,6,0,1,0,5,78,5,73,0
331,False,5828,2,0,0,1,1,58,5,51,2
332,False,8392,4,0,0,0,4,59,6,52,1
333,True,5175,11,0,0,3,8,194,23,169,2
334,True,28179,109,0,12,16,81,1165,169,953,43
335,True,10245,26,1,3,11,11,242,58,163,21
336,False,1862,6,0,0,0,6,92,10,80,2
337,False,4337,5,0,0,1,4,54,9,41,4
338,True,43777,21,0,2,3,16,469,101,361,7
339,False,1797,0,0,0,0,0,25,5,20,0
340,True,4574,11,0,1,0,10,164,32,129,3
341,False,1732,2,0,0,0,2,44,4,37,3
342,True,44821,35,1,1,9,24,896,166,710,20
343,False,2604,6,0,0,0,6,62,12,49,1
344,True,57559,78,1,3,28,46,1232,77,1134,21
345,False,3733,4,0,0,0,4,36,14,21,1
346,False,9141,0,0,0,0,0,77,13,61,3
347,True,10685,3,0,0,2,1,541,9,529,3
348,False,829,7,0,0,0,7,17,8,9,0
349,False,5931,2,0,0,0,2,58,13,45,0
350,True,199134,1036,6,25,390,615,2368,470,1662,236
351,True,36643,15,0,0,2,13,334,45,287,2

In [37]:
vanregr = LogisticRegression(penalty='l2', C=1e9) 
vanregr.fit(x_train, y_train)

y_train_pred = vanregr.predict(x_train)
y_test_pred = vanregr.predict(x_test)



print(vanregr.score(x_train, y_train))
origparams = vanregr.coef_[0]
print(origparams)

0.6690391459074733
[-9.50434812e-05  8.48468758e-04  1.67132134e-05  8.87092528e-05
  3.02860340e-04  4.40185951e-04  8.76194122e-03  1.40422496e-03
  7.27510956e-03  8.26067080e-05]

/Users/katrinajohnson/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [38]:
print(classification_report(y_train, y_train_pred))

              precision    recall  f1-score   support

       False       0.95      0.30      0.46       130
        True       0.62      0.99      0.76       151

   micro avg       0.67      0.67      0.67       281
   macro avg       0.79      0.64      0.61       281
weighted avg       0.77      0.67      0.62       281

In [39]:
pd.crosstab(y_train, y_train_pred)

col_0                  False  True
Property crime binary
False                     39     91
True                       2    149

# Ridge Regression using Sklearn

In [48]:
ridgeregr = LogisticRegression(penalty='l2', C=1.0) 
ridgeregr.fit(x_train, y_train)


print(ridgeregr.score(x_train, y_train))
origparams = ridgeregr.coef_[0]
print(origparams)

0.6690391459074733
[-9.50429375e-05  8.48464596e-04  1.67131062e-05  8.87087978e-05
  3.02858753e-04  4.40183939e-04  8.76190504e-03  1.40421918e-03
  7.27507942e-03  8.26064505e-05]

/Users/katrinajohnson/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [49]:
print(ridgeregr.score(x_test, y_test))

0.6515151515151515

#Step 2a.

df.insert(, 'Property crime binary', '')
df

# Lasso Regression Model using Sklearn

In [42]:
lassoregr = LogisticRegression(penalty='l1', C=2.5) 
lassoregr.fit(x_train, y_train)


print(lassoregr.score(x_train, y_train))
origparams = lassoregr.coef_[0]
print(origparams)

/Users/katrinajohnson/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

0.900355871886121
[ 6.13934463e-05 -1.42335334e-03 -2.55856414e-02  8.64489104e-02
 -3.12305037e-03 -7.12595987e-03  4.14994115e-04  5.56280702e-03
  3.37079908e-03 -1.08461990e-02]

/Users/katrinajohnson/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [43]:
print(lassoregr.score(x_test, y_test))

0.8636363636363636

In [44]:
y_train.value_counts()

True     151
False    130
Name: Property crime binary, dtype: int64

In [45]:
y_test.value_counts()

True     34
False    32
Name: Property crime binary, dtype: int64